### ISSUE TITLE
TODO/FAZER

### ISSUE THREAD

**Issue by stelsonip** [stelsonip/FLAPPY-BIRD#1]
**Criar a estrutura inicial do Jogo:**
- [ ] Setup inicial do canvas
- [ ] Desenhar o Flappy Bird na tela
- [ ] Game Loop
- [ ] Desenhar o resto do cenário
- [ ] Adicionar tela de início

**Comment by stelsonip** [comment]
**DOING/FAZENDO**

**Comment by stelsonip** [comment]
**DONE/FEITO**
- [ ] Criar roteiros e fluxo do projecto
- [ ] HTML inicial do projecto
- [ ] Separar os sprites
